# Generated by Django 4.2.1 on 2023-07-05 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='csv',
        ),
    ]
