# Generated by Django 4.2.1 on 2023-07-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_remove_artist_csv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='dob',
            field=models.DateTimeField(null=True),
        ),
    ]
