# Generated by Django 4.2.1 on 2023-07-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_remove_artist_csv'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='csv',
            field=models.FileField(null=True, upload_to='csv'),
        ),
    ]
